before_install:
- openssl aes-256-cbc -K $encrypted_f0eda51f49d6_key -iv $encrypted_f0eda51f49d6_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
script:
  - ssh root@116.62.198.23 "cd /root/incpad/packages/storybook/scripts && ./build.sh"
branches:
  only:
  - Feat_for_storybook